### ISSUE TITLE
Consistent use of the New Topic button

### ISSUE THREAD

**Issue by henrywright** [NodeBB/nodebb-theme-persona#144]
The _New Topic_ button seems to be used on certain pages only. These are the pages (with a list of topics on them) that the button doesn't seem to be on:

 - example.com/unread
 - example.com/popular
 - example.com/popular/daily
 - example.com/popular/weekly
 - example.com//popular/monthly
 - example.com/popular/alltime
 - example.com/user/_henrywright_/topics
 - example.com/user/_henrywright_/watched

Is it worth adding the button to these?

__Edit__ 

I'm not so sure it's a good idea because if you created a topic from, let's say the _unread_ page, then which category does the topic get filed under? Feel free to close this issue as it might have been a bad idea.

**Comment by julianlam** [comment]
It's not a bad idea, we've toyed with the problem before, and so that's why there's a category selector in the composer itself.

The Rocket Redux theme takes this a step further and introduces a new topic button across the entire site, but that may be taking it too far:

![selection_003](https://cloud.githubusercontent.com/assets/923011/9549539/8ebaa9e6-4d74-11e5-9c44-1454a5e93a85.png)

![selection_004](https://cloud.githubusercontent.com/assets/923011/9549541/9268ab10-4d74-11e5-9d04-c6d05a7ed8c2.png)

**Comment by henrywright** [comment]
I just gave rocket-redux a spin and kinda like the "post a new topic from anywhere" idea. It makes things easier for the user. And the category selector in the composer solves the "which category" problem very well.

Regarding Persona, if you were to have something like that, I suppose the question is where would the button sit?

**Comment by julianlam** [comment]
Given Persona's lean towards material design, I'd totally go for a bright red `+` at the bottom-right of my screen.

**Comment by henrywright** [comment]
That'd work! Although don't forgot there's already a bright red + when the composer is open:

![composer](https://cloud.githubusercontent.com/assets/1963288/9550749/169390aa-4da5-11e5-9df0-2aecf6c761aa.png)

Might need to make sure the two aren't confused.

**Comment by julianlam** [comment]
Oh, right. @psychobunny, your thoughts? :smile:
