### ISSUE TITLE
Deleted posts should not have voting controls displayed

### ISSUE THREAD

**Issue by julianlam** [NodeBB/nodebb-theme-persona#32]
@frissdiegurke said:
> I'd like to upvote him for this but deleted posts cannot get votes :( btw: @psychobunny shouldn't the vote-buttons get hidden then? :stuck_out_tongue:

**Comment by frissdiegurke** [comment]
side-question: does reputation of deleted posts get removed from the users account?
I don't think so (since highly-negative rated posts should get deleted without user-improvement) which results in: The voting-amount should still be visible then (maybe just disable / gray-out the buttons).

Same for self-owned posts.

**Comment by frissdiegurke** [comment]
To fast solution... @psychobunny did you read my comment above? Don't you think the voting-number should still be visible too?
And for self-owned posts the same since you cannot vote for them either. Would be best to add a class to the `component="post"` then like.
