### ISSUE TITLE
Timeago doesn't show localized version

### ISSUE THREAD

**Issue by orweinberger** [NodeBB/nodebb-theme-persona#378]
Something broke between v6.0.1 to v6.1.0 that causes the timeago strings to appear in English regardless of the general language selected in the admin section.

I suspect its due to this change, but not sure https://github.com/NodeBB/nodebb-theme-persona/commit/788399c86da8aab33a391baaa58333f8798ce537

**Comment by barisusakli** [comment]
@orweinberger do you have any custom JS by any chance? Looks like we need to move that down to the footer as well since using jquery in custom js will cause an error right now.

https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/header.tpl#L19-L21

That will have to go before the closing body tag

**Comment by orweinberger** [comment]
No custom JS.

**Comment by julianlam** [comment]
Custom js will need to be wrapped in an event listener for the page load event, persona commits will show it

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/5971
