### ISSUE TITLE
Upvote and Downvote

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-theme-persona#48]
Notifications:
Πέτρος Φεργκιούδης has upvoted your post in Wrong message shown for invalid username and password.
https://community.nodebb.org/topic/4159/wrong-message-shown-for-invalid-username-and-password/12

I have opened a link (post id 12) and nothing upvoted or downvoted here. A new user so he probably used upvote & downvote in a short time just to see how it works.

But when you scroll to post id 8 you'll see -1 rating.
https://community.nodebb.org/topic/4159/wrong-message-shown-for-invalid-username-and-password/8

There is no information who downvoted this post (in the same time it works for upvoted posts) and there was no notification about that.

**Comment by psychobunny** [comment]
I think we don't show downvotes on purpose, similar to stackoverflow, might make you seem very antagonistic. The whole downvoting idea doesn't really work well for communities anyways (more so for q&a forums), which is why we added a setting to remove downvoting. 

I plan to remove it on our community as well, but I'm keeping it up until 1.0 so that we can continue using our community for the secondary purpose of live testing our latest code ;)


p.s. in any case, this is a core issue not theme issue, so if you like, feel free to reissue on core tracker
