### ISSUE TITLE
Dropdowns from header go under composer

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-theme-persona#50]
Steps to reproduce:
1. Go to random topic and edit it or start replying
2. Real-time notifications can start showing when you're busy adding new content
3. You're interested what's going on and hit Notifications, Chats or Profile to expand their windows
4. You realize that you've to hit Discard in Composer or open your NodeBB in new browser tab/window to read Notifications or Chats

Notifications window should expand/float on top of Composer window.

**Comment by barisusakli** [comment]
![image](https://cloud.githubusercontent.com/assets/2583394/12959078/75116ad8-d03d-11e5-875c-d4cb87ba4531.png)

**Comment by julianlam** [comment]
According to the bootstrap modal variables, this is by-design, as a dropdown will have lower priority than modals (which chats and composer are considered), otherwise they may accidentally overlap things like the modals themselves (which are designed to be atop of everything) and the modal backdrop, if any.
