### ISSUE TITLE
Font boosting inconsistent

### ISSUE THREAD

**Issue by sadaszewski** [NodeBB/nodebb-theme-persona#542]
On mobile Webkit [font boosting](https://ux.stackexchange.com/questions/80931/is-font-boosting-good-ux) kicks in for some elements while not for others. For example for the posts shown in the topic view it bumps font-size from 14px to 15.4px. On the other hand for the Recent Posts widget it stays at 14px, which is clearly unintended and causes some small degree of visual distraction. The way to disable this in CSS3 is the [text-size-adjust](https://developer.mozilla.org/fr/docs/Web/CSS/text-size-adjust) attribute but it does not seem to be properly supported by Webkit yet. A [workaround](https://stackoverflow.com/questions/13430897/how-to-override-font-boosting-in-mobile-chrome) seems to be to set the max-height of the element to a huge value. It can be done in custom CSS, just bringing this to your attention and capturing it here.

**Comment by sadaszewski** [comment]
PS. This can be debugged only using Remote USB debugging of chrome on a real Android device. The mobile view in desktop browser does not employ font boosting.

**Comment by julianlam** [comment]
Hm... I think while my gut feeling is that font boosting is an affront to my delicate design sensitivites, I just need to get over it :smile: (not that I have a lot of design chops to begin with...)

That said, the issue seems to be here that the font in the topic is boosted, while the font in the recent posts is not. This is because the font size is explicitly set in the recent posts widget:

![image](https://user-images.githubusercontent.com/923011/153232856-8dfed77a-c1f1-47d4-bda1-487277c64ef0.png)

Why? Beats me, because removing it changes nothing, so I think this is the correct course of action here. @sadaszewski If you can find other places where there are inconsistencies, we can look into them one by one.

**Comment by julianlam** [comment]
I can't reproduce it on my device (Google Pixel 5a on Chrome), so it could be this only happens on older devices?

Nevertheless, hopefully I've addressed it in v5.0.7
